### ISSUE TITLE
Remove event listeners in detached

### ISSUE THREAD

**Issue by dbatiste** [BrightspaceUI/tile#29]
For the following snippet, we should have a corresponding `detached` method to remove the listeners.  Otherwise, if the element is detached and reattached we'll end up with multiple event handlers wired up.  Note: this means we need to be careful about the reference we are removing... the call to `bind` results in a different function... so the function reference added as a listener should be the same function reference that is removed.

https://github.com/BrightspaceUI/tile/blob/e4cc281324d9cb2b43958e750a172d00a98546b9/d2l-image-tile.html#L204-L207

What we want is:

```
ready: function() {
	this._someHandler = this._someHandler.bind(this);
},

attached: function() {
	Polymer.RenderStatus.afterNextRender(this, function() { 
		someElement.addEventListener('some-event', this._someHandler, true);
	}.bind(this));
},

detached: function() {
	someElement.removeEventListener('some-event', this._someHandler, true);
}
```
 Also note: the capture argument needs to match for the handler to be removed correctly.

**Comment by dlockhart** [comment]
Either that or use the [`listeners` collection](https://www.polymer-project.org/1.0/docs/devguide/events#event-listeners), which will automatically add/remove the listeners.

```
listeners: {
    'some-event': '_someHandler'
}
```

**Comment by dbatiste** [comment]
Yep... or that.  Would be much less code.  

Might still need `addEventListener` and `removeEventListener` in this case if `capture=true` is really required.

**Comment by ChrisKraljevicD2L** [comment]
I'm going to do a bit of testing with `capture=true` removed (and with `listeners` specified) and I'll see what blows up if anything.

**Comment by jstefaniuk-d2l** [comment]
#34 merged
