### ISSUE TITLE
Overflow being used to hide menu?

### ISSUE THREAD

**Issue by dbatiste** [BrightspaceUI/tile#31]
It looks like the menu is hidden via overflow, which would still be accessible with keyboard.  Is this the intent?

https://github.com/BrightspaceUI/tile/blob/e4cc281324d9cb2b43958e750a172d00a98546b9/d2l-image-tile.html#L16-L18

https://github.com/BrightspaceUI/tile/blob/e4cc281324d9cb2b43958e750a172d00a98546b9/d2l-image-tile.html#L24-L32

**Comment by dbatiste** [comment]
It seems like the hiding/showing of the menu can be simplified, as well as the corresponding template-DOM for it.  It would be good to simply set `display:none;` on the dropdown when we don't want it to show up.

**Comment by jstefaniuk-d2l** [comment]
I don't think the overflow is being used to hide the menu, I _think_ it was there for fixing a visual glitch with the hover effect (based on: https://github.com/BrightspaceUI/tile/commit/4e976a8d056c472401a3f364663a0da344e38384), but can't remember for the life of me

**Comment by ChrisKraljevicD2L** [comment]
I've tested with these `overflow` rules removed in chrome/firefox/edge/safari and all appears OK. This will be fixed in #27

**Comment by jstefaniuk-d2l** [comment]
https://github.com/BrightspaceUI/tile/pull/27 merged
