### ISSUE TITLE
Specifying fallback color

### ISSUE THREAD

**Issue by dbatiste** [BrightspaceUI/tile#32]
Are we able to use the newer version, where `var` is not specified on the fallback variable?
https://github.com/BrightspaceUI/tile/blob/e4cc281324d9cb2b43958e750a172d00a98546b9/d2l-image-tile.html#L45

```
background: var(--d2l-image-tile-image-background, --d2l-color-regolith); 
```
Or does that not work in Polymer 1?

**Comment by dlockhart** [comment]
We should be using the one without `var` yes, good catch. It's a requirement I believe to be fully hybridized. See "update custom property syntax" under this section:
https://www.polymer-project.org/2.0/docs/upgrade#shadow-dom-styles

**Comment by jstefaniuk-d2l** [comment]
Closing this as per the discussion here: https://github.com/BrightspaceUI/tile/pull/36
