### ISSUE TITLE
Animating box-shadow is expensive

### ISSUE THREAD

**Issue by dbatiste** [BrightspaceUI/tile#33]
Generally, we should try to avoid animating box-shadow.  It results in layout and paint (https://csstriggers.com/box-shadow), which can be expensive.  I'd question whether this is _really_ necessary.

https://github.com/BrightspaceUI/tile/blob/e4cc281324d9cb2b43958e750a172d00a98546b9/d2l-image-tile.html#L115

**Comment by jstefaniuk-d2l** [comment]
Hmm, perhaps we could switch to the way listed here: http://tobiasahlin.com/blog/how-to-animate-box-shadow/ (Animating the opacity of a pseudo-element which always has the box-shadow set)
